package net.codejava.hibernate;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nicom
 */
public class InsertVisit extends javax.swing.JFrame {

    /**
     * Creates new form InsertVisit
     */
    
    private ClinicManagerEM jpaManager;
    private levelDBManager ldbManager;
    private String docID;
    private String patient;
    private String date;
    private DoctorWindow docWind;
    
    public InsertVisit(ClinicManagerEM m, levelDBManager l, String d, String p, String dt, DoctorWindow dw) {
        initComponents();
        jpaManager = m;
        ldbManager = l;
        docID = d;
        patient = p;
        date = dt;
        docWind = dw;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TFPatient = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFDocID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TFType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        CBResult = new javax.swing.JComboBox<>();

        setTitle("Insert visit");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Patient");

        TFPatient.setEnabled(false);

        jLabel2.setText("Doctor ID");

        TFDocID.setEnabled(false);

        jLabel3.setText("Date");

        TFDate.setEnabled(false);

        jLabel4.setText("Examination type");

        jLabel5.setText("Result");

        SubmitButton.setText("Submit");
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
        });

        CBResult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "not available", "negative ", "positive" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(SubmitButton)
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFPatient)
                    .addComponent(TFDocID)
                    .addComponent(TFDate)
                    .addComponent(TFType)
                    .addComponent(CBResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFDocID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CBResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(SubmitButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
        // TODO add your handling code here:
        if(TFType.getText().equals("")) {
            new ErrorWindow("Error: insert an examination type.").setVisible(true);
        }
        else {
            Patient p = jpaManager.readPatient(patient);
            int id = p.getPatientId();
           // jpaManager.createExamination(id, Integer.parseInt(docID), TFType.getText(), CBResult.getSelectedItem().toString(), date); //TO COMMENT
            ldbManager.putExamination(p.getTaxCode(), Integer.parseInt(docID), TFType.getText(), CBResult.getSelectedItem().toString(), date);
            docWind.updateTable(docID);
            setVisible(false);

            ldbManager.dumpLevelDB();
        }
    }//GEN-LAST:event_SubmitButtonMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        TFDocID.setText(docID);
        TFDate.setText(date);
        TFPatient.setText(patient);       
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBResult;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField TFDate;
    private javax.swing.JTextField TFDocID;
    private javax.swing.JTextField TFPatient;
    private javax.swing.JTextField TFType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}