package net.codejava.hibernate;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nicom
 */
public class PatientWindow extends javax.swing.JFrame {

    /**
     * Creates new form PatientWindow
     */
    
    private ClinicManagerEM jpaManager;
    private levelDBManager ldbManager;
    private String taxcode;
    
    public PatientWindow(ClinicManagerEM m, levelDBManager l, String t) {
        initComponents();
        jpaManager = m;
        ldbManager = l;
        taxcode = t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonInfo = new javax.swing.JButton();
        TFPatient = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ButtonDelete = new javax.swing.JButton();
        ButtonDeleteaccount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButtonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ButtonInfo.setText("Change Info");
        ButtonInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonInfoMouseClicked(evt);
            }
        });

        TFPatient.setEnabled(false);

        jLabel1.setText("Tax code");

        ButtonDelete.setText("Delete visit");
        ButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonDeleteMouseClicked(evt);
            }
        });

        ButtonDeleteaccount.setText("Delete account");
        ButtonDeleteaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonDeleteaccountMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Visit ID", "Doc Name", "Doc Surname", "Doc Mail", "P Name", "P Surname", "P Taxcode", "P Mail", "Date", "Type", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ButtonLogout.setText("Logout");
        ButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TFPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonInfo)
                        .addGap(69, 69, 69)
                        .addComponent(ButtonDelete)
                        .addGap(69, 69, 69)
                        .addComponent(ButtonDeleteaccount)))
                .addContainerGap(463, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonLogout)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDelete)
                    .addComponent(ButtonInfo)
                    .addComponent(ButtonDeleteaccount))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonInfoMouseClicked

        PatientSignUp change_info = new PatientSignUp(jpaManager, ldbManager, this);
        change_info.setVisible(true);
        change_info.setTitle("Patient Info");
        change_info.set_taxcode(TFPatient.getText());
        change_info.disable_textFields();       
    }//GEN-LAST:event_ButtonInfoMouseClicked

    private void ButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDeleteMouseClicked
        // TODO add your handling code here:
        int rowIndex = jTable1.getSelectedRow();
        if(rowIndex == -1) {
            new ErrorWindow("Error: Select in the table the visit you want to remove.").setVisible(true);
        }
        else {
            String visitID = jTable1.getValueAt(rowIndex, 0).toString();
            //jpaManager.deleteExamination(visitID); //TO COMMENT
            ldbManager.deleteExaminations(visitID);

            ldbManager.dumpLevelDB();

            //List<Examination> list = jpaManager.readPatientExaminations(TFPatient.getText());
            List<Examination> list = ldbManager.readPatientExamination(TFPatient.getText());
            DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
            d.setRowCount(0);
            int num_col = 11;
            Object[] row = new Object[num_col];

            for(int j=0; j<list.size(); ++j) {
                Examination e = list.get(j);
                row[0] = e.getId();
                row[1] = e.getDoctor().getName();
                row[2] = e.getDoctor().getSurname();
                row[3] = e.getDoctor().getEmail();
                row[4] = e.getPatient().getName();
                row[5] = e.getPatient().getSurname();
                row[6] = e.getPatient().getPatientId();
                row[7] = e.getPatient().getEmail();
                row[8] = e.getDate();
                row[9] = e.getType();
                row[10] = e.getResult();
                d.addRow(row);
            }
        }
    }//GEN-LAST:event_ButtonDeleteMouseClicked

    private void ButtonDeleteaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDeleteaccountMouseClicked
        // TODO add your handling code here:
        jpaManager.deletePatient(TFPatient.getText());
        
        List<Examination> list = ldbManager.readPatientExamination(TFPatient.getText());
        for(int i=0; i<list.size(); ++i) {
            Examination e = list.get(i);
            ldbManager.deleteExaminations(Integer.toString(e.getId()));
        }
        
        ldbManager.deletePatient(TFPatient.getText());
        
        
 
        this.setVisible(false);
        new MainWindow(jpaManager, ldbManager).setVisible(true);
        
        ldbManager.dumpLevelDB();
    }//GEN-LAST:event_ButtonDeleteaccountMouseClicked

    private void ButtonLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLogoutMouseClicked
        // TODO add your handling code here:
        new MainWindow(jpaManager, ldbManager).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonLogoutMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        TFPatient.setText(taxcode);
        
        //List<Examination> list = jpaManager.readPatientExaminations(TFPatient.getText());
        List<Examination> list = ldbManager.readPatientExamination(TFPatient.getText());
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
        d.setRowCount(0);
        int num_col = 11;
        Object[] row = new Object[num_col];
        
        for(int j=0; j<list.size(); ++j) {
            Examination e = list.get(j);
            row[0] = e.getId();
            row[1] = e.getDoctor().getName();
            row[2] = e.getDoctor().getSurname();
            row[3] = e.getDoctor().getEmail();
            row[4] = e.getPatient().getName();
            row[5] = e.getPatient().getSurname();
            row[6] = e.getPatient().getPatientId();
            row[7] = e.getPatient().getEmail();
            row[8] = e.getDate();
            row[9] = e.getType();
            row[10] = e.getResult();
            d.addRow(row);
        }      
    }//GEN-LAST:event_formWindowOpened

    void updateTable(String patient) {
        List<Examination> list = ldbManager.readPatientExamination(patient);
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
        d.setRowCount(0);
        int num_col = 11;
        Object[] row = new Object[num_col];
        
        for(int j=0; j<list.size(); ++j) {
            Examination e = list.get(j);
            row[0] = e.getId();
            row[1] = e.getDoctor().getName();
            row[2] = e.getDoctor().getSurname();
            row[3] = e.getDoctor().getEmail();
            row[4] = e.getPatient().getName();
            row[5] = e.getPatient().getSurname();
            row[6] = e.getPatient().getPatientId();
            row[7] = e.getPatient().getEmail();
            row[8] = e.getDate();
            row[9] = e.getType();
            row[10] = e.getResult();
            d.addRow(row);
        }      
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonDeleteaccount;
    private javax.swing.JButton ButtonInfo;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JTextField TFPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}