package net.codejava.hibernate;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nicom
 */
public class PatientWindow extends javax.swing.JFrame {

    /**
     * Creates new form PatientWindow
     */
    
    private ClinicManagerEM manager;
    
    public PatientWindow(ClinicManagerEM m) {
        initComponents();
        manager = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpButton = new javax.swing.JButton();
        ButtonInfo = new javax.swing.JButton();
        TFPatient = new javax.swing.JTextField();
        ButtonTests = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ButtonDelete = new javax.swing.JButton();
        ButtonDeleteaccount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setTitle("Patient");

        SignUpButton.setText("Sign Up");
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseClicked(evt);
            }
        });
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        ButtonInfo.setText("Change Info");
        ButtonInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonInfoMouseClicked(evt);
            }
        });

        TFPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPatientActionPerformed(evt);
            }
        });

        ButtonTests.setText("Show your tests");
        ButtonTests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonTestsMouseClicked(evt);
            }
        });
        ButtonTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTestsActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter your tax code");

        ButtonDelete.setText("Delete visit");
        ButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonDeleteMouseClicked(evt);
            }
        });
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonDeleteaccount.setText("Delete account");
        ButtonDeleteaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonDeleteaccountMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Visit ID", "Doc Name", "Doc Surname", "Doc Mail", "P Name", "P Surname", "P Taxcode", "Date", "Type", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TFPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SignUpButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonInfo)
                        .addGap(36, 36, 36)
                        .addComponent(ButtonTests)
                        .addGap(35, 35, 35)
                        .addComponent(ButtonDelete)
                        .addGap(39, 39, 39)
                        .addComponent(ButtonDeleteaccount)))
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUpButton)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTests)
                    .addComponent(ButtonDelete)
                    .addComponent(ButtonInfo)
                    .addComponent(ButtonDeleteaccount))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void TFPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPatientActionPerformed

    private void SignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientSignUp(manager).setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_SignUpButtonMouseClicked

    private void ButtonInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonInfoMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PatientSignUp change_info = new PatientSignUp(manager);
                change_info.setVisible(true);
                change_info.setTitle("Patient Info");
                change_info.set_taxcode(TFPatient.getText());
                change_info.disable_textFields();
                
            }
        });
        this.dispose();
    }//GEN-LAST:event_ButtonInfoMouseClicked

    private void ButtonTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTestsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTestsActionPerformed

    private void ButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDeleteMouseClicked
        // TODO add your handling code here:
        int rowIndex = jTable1.getSelectedRow();
        String visitID = jTable1.getValueAt(rowIndex, 0).toString();
        Patient p = manager.readPatient(TFPatient.getText());
        manager.deleteVisit(visitID, p.getPatientId());
        
        List<Examination> list = manager.readPatientExaminations(TFPatient.getText());
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
        d.setRowCount(0);
        int num_col = 10;
        Object[] row = new Object[num_col];
        
        for(int j=0; j<list.size(); ++j) {
            Examination e = list.get(j);
            row[0] = e.getId();
            row[1] = e.getDoctor().getName();
            row[2] = e.getDoctor().getSurname();
            row[3] = e.getDoctor().getEmail();
            row[4] = e.getPatient().getName();
            row[5] = e.getPatient().getSurname();
            row[6] = e.getPatient().getTaxCode();
            row[7] = e.getDate();
            row[8] = e.getType();
            row[9] = e.getResult();
            d.addRow(row);
        }
    }//GEN-LAST:event_ButtonDeleteMouseClicked

    private void ButtonTestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonTestsMouseClicked
        // TODO add your handling code here:
        List<Examination> list = manager.readPatientExaminations(TFPatient.getText());
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
        d.setRowCount(0);
        int num_col = 10;
        Object[] row = new Object[num_col];
        
        for(int j=0; j<list.size(); ++j) {
            Examination e = list.get(j);
            row[0] = e.getId();
            row[1] = e.getDoctor().getName();
            row[2] = e.getDoctor().getSurname();
            row[3] = e.getDoctor().getEmail();
            row[4] = e.getPatient().getName();
            row[5] = e.getPatient().getSurname();
            row[6] = e.getPatient().getTaxCode();
            row[7] = e.getDate();
            row[8] = e.getType();
            row[9] = e.getResult();
            d.addRow(row);
        }
    }//GEN-LAST:event_ButtonTestsMouseClicked

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonDeleteaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDeleteaccountMouseClicked
        // TODO add your handling code here:
        manager.deletePatient(TFPatient.getText());
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
        d.setRowCount(0);
    }//GEN-LAST:event_ButtonDeleteaccountMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow(manager).setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonDeleteaccount;
    private javax.swing.JButton ButtonInfo;
    private javax.swing.JButton ButtonTests;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JTextField TFPatient;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
